### ISSUE TITLE
Slider Image -> Post Editor not showing

### ISSUE THREAD

**Issue by bdalina54** [iGovPhil/gwt-wordpress#13]
When i add new Slide Image, only title is showing, the post Editor is not showing, i am not able to add slider image in a post editor, only the slider URL appears, even if i add slider url, still not working. I'm using the latest version of wordpress Version 4.9.1, Your old version is working. Please fix.

**Comment by v0j** [comment]
Please refer to issue #11

**Comment by bdalina54** [comment]
Issue #11, did not help. 
The your slider "insert url" still didn't work. 

So I go directly into the code of "wp-content/themes/gwt/inc/banner.php" and enter the shortcode of smart slider.

line 31....................<?php if($banner_slider = efs_get_slider()): ?>
line 32.......................................<?php if(govph_displayoptions( 'govph_slider_full' ) == 'active'): ?>
line 33.....................................................<div id="banner-slider" class="large-12 hide-for-small-only">
line 34......................................<?php else: ?>
line 35.....................................................<div id="banner-slider" class="<?php echo $banner_class ?>">
line 36.....................................<?php endif; ?>
line 37.....................................................<?php echo $banner_slider ?>
line 38.....................................................<?php echo do_shortcode('[smartslider3 slider=2]'); ?>
line 39.....................................................</div>
line 40....................<?php endif; ?>

The slider shows up.

**Comment by v0j** [comment]
You haven't specified that you are using a third party plugin. Unfortunately we only have limited support for code modification specifically for third party plugin such as smart slider 3.
