### ISSUE TITLE
CSS styling of menu on home page

### ISSUE THREAD

**Issue by brasalan** [iGovPhil/gwt-wordpress#14]
Ugly alignment and no hover effects of text on menus in the home page. Pls provide fix

**Comment by v0j** [comment]
To provide you further support please give the following details:
GWT version
screenshot of your issue

**Comment by brasalan** [comment]
hello,

GWT-Wordpress 25.2 theme.

Please access http://rfo02.da.gov.ph

As you can see for example, if you hover on menu About US> Mandate, Vision
and Mission there is no hover effect and because of that, reading the
submenus when the title is long makes it very confusing for the readers.
Same readability problem I saw with the DICT website. Although, it looks
fine on a mobile device but on a wider screen, it doesn't.

**Comment by v0j** [comment]
[GWT-wordpress 25.3 has been release](https://github.com/iGovPhil/gwt-wordpress/releases/latest) to fix the word wrapping issue.

Please download and update your theme.

**Comment by brasalan** [comment]
Thanks very much for the quick fix!
