### ISSUE TITLE
Customized Widget Bug

### ISSUE THREAD

**Issue by kiracrack** [iGovPhil/gwt-wordpress#18]
Customized widget under "Right Sidebar" Section is not functional. it can display if both left and right sidebar are configure together. we can use single sidebar in the right side. theme shows nothing on the page preview
![image](https://user-images.githubusercontent.com/23105830/42624913-16e62330-85f9-11e8-9f24-e93b9f88a0a8.png)

**Comment by v0j** [comment]
The sidebar system is dynamic. Simply add a widget on right side bar and it will display accordingly. Same goes with left side bar.

**Comment by kiracrack** [comment]
yes i did. but nothing is display

**Comment by kiracrack** [comment]
as you can see on the attachment. theres calendar widget and archives

**Comment by v0j** [comment]
Have you tried adding widget via appearance > widget?

**Comment by v0j** [comment]
no repy. Closing issue. You can re-open them if this does not yet solve the issue..
