### ISSUE TITLE
Theme styling options is not working

### ISSUE THREAD

**Issue by carl-alberto** [iGovPhil/gwt-wordpress#19]
https://content.screencast.com/users/craxtech/folders/Jing/media/3791b842-2c23-404d-9bc4-eafccf8a488e/00000107.png

**Comment by v0j** [comment]
apologies for the delay of response, I need more information on what version of wordpress and gwt version this is to reproduce the issue to be able fix the issue easier.

Thanks,

**Comment by v0j** [comment]
Just installed this to a fresh version of wordpress 5.0 and I cannot reproduce the issue. Needs more info. For now closing the issue.

If you can provide additional info, just re-open this ticket.
