### ISSUE TITLE
Theme options color picker not showing

### ISSUE THREAD

**Issue by voyagine** [iGovPhil/gwt-wordpress#20]
Having the same issue for theme options.  I can't change any color (header, background).  This problem is reflected in any other plugins, no more access to color.  
![problem theme option](https://user-images.githubusercontent.com/9678168/49730974-dd2fa480-fcb4-11e8-9171-b770b149df29.JPG)

**Comment by v0j** [comment]
We have released a patch release to display color options:
https://github.com/iGovPhil/gwt-wordpress/releases/tag/25.3.1

please test and confirm if this works successfully.

Thanks,
