### ISSUE TITLE
Alignment of Picture with visual editor of wordpress

### ISSUE THREAD

**Issue by voyagine** [iGovPhil/gwt-wordpress#21]
I can't align a media in a text.  In the visual editor, everything seems to be fine but when I look at the website, it's not align any more.  How can I solve this problem?
![problem alignment picture in editor](https://user-images.githubusercontent.com/9678168/49731142-57602900-fcb5-11e8-81aa-1ab53a94439d.JPG)
![problem alignment of picture](https://user-images.githubusercontent.com/9678168/49731147-5c24dd00-fcb5-11e8-8c27-ec9a207ed5f7.JPG)

**Comment by voyagine** [comment]
Problem is with version WordPress 5 and also 4.9.8.  No conflict with other plugin.  I tried to install the template on an empty wordpress and I have the same issues

**Comment by v0j** [comment]
Added support for native class alignleft and alignright to the theme to display it properly.
Please see release [25.3.1 for more info](https://github.com/iGovPhil/gwt-wordpress/releases/tag/25.3.1)

Let me know if this works.
