### ISSUE TITLE
“Warning” on PHP 7.3

### ISSUE THREAD

**Issue by picepice** [iGovPhil/gwt-wordpress#33]
Warning: count(): Parameter must be an array or an object that implements Countable in ../wp-content/themes/lgwt-wordpress-master\inc\function-options.php on line 59

Warning: array_merge(): Expected parameter 2 to be an array, bool given in ../wp-content/themes/lgwt-wordpress-master\inc\function-options.php on line 59

PHP 7.3
XAMPP

**Comment by jhunJT** [comment]
How did you deal with this problem?

**Comment by lamerock** [comment]
> How did you deal with this problem?

may I know the URL of your site?
