### ISSUE TITLE
error footer.js and gwtpst.js

### ISSUE THREAD

**Issue by picepice** [iGovPhil/gwt-wordpress#34]
![gwt error](https://user-images.githubusercontent.com/8589745/61580287-b555c880-ab42-11e9-89a9-14b05e850457.png)

lookslike gwhs.i.gov.ph is down..

**Comment by v0j** [comment]
Hi Picepice,

This may be a cache issue causing failing to load. Simply wait for a few minutes and try again.

**Comment by picepice** [comment]
Hello ive tried it again but still the error occurs.. I also checked some government website and found out that even the ovp has the error..

http://ovp.gov.ph/

https://downforeveryoneorjustme.com/gwhs.i.gov.ph

![ovp](https://user-images.githubusercontent.com/8589745/62215565-ca034d80-b3d9-11e9-978d-d936d655200b.png)
![ovp2](https://user-images.githubusercontent.com/8589745/62215579-cf609800-b3d9-11e9-8437-a9bb9fe7056c.png)

**Comment by picepice** [comment]
ALL GOOD NOW.. Its not an issue on caching..  gwhs.i.gov.ph is down for 12 days..

**Comment by v0j** [comment]
It seems that there have been issue found within the server.

Thank you for reporting the issue.
