### ISSUE TITLE
Can't access the customize panel

### ISSUE THREAD

**Issue by 0821zxc99** [iGovPhil/gwt-wordpress#49]
![image](https://user-images.githubusercontent.com/95012012/143385354-d3244f53-2fa1-4556-9857-3b99f1924e12.png)
I haven't open the website for awhile but when I came back to check it, it has already an error. The last time I open this panel, it's okay. Thank you

**Comment by lamerock** [comment]
Just for reference. You will get this error if you are using PHP 8. Changing to PHP 7.4+ will fixed the error.
