### ISSUE TITLE
Can't access the dashboard

### ISSUE THREAD

**Issue by 0821zxc99** [iGovPhil/gwt-wordpress#50]
![image](https://user-images.githubusercontent.com/95012012/143386716-46325339-fa15-4efc-b6ac-685107d7d77c.png)

**Comment by lamerock** [comment]
Are you running Wordpress locally like using WAMP?

**Comment by 0821zxc99** [comment]
No sir. This is not a local site. I've been producing a backup site to decommission our previous site because of the redirection/malware attack.

**Comment by 0821zxc99** [comment]
Can I ask also sir if how can we get rid the redirection attack on our site? When we try to access our site peace.gov.ph thru desktop, it is accessible but when we try to access it on our mobile devices, it's redirecting to other site.

**Comment by lamerock** [comment]
> Can I ask also sir if how can we get rid the redirection attack on our site? When we try to access our site peace.gov.ph thru desktop, it is accessible but when we try to access it on our mobile devices, it's redirecting to other site.

First, check if all the plugins are updated. If not, update them. Also check the .htaccess file if they made changes to the redirection. You may install the plugin Wordfence or Ithemes Security to scan for Malware. You can also use the ClamAV included in the cPanel (this may depend on your hosting service).

**Comment by rajeem** [comment]
Hi @0821zxc99
Agree with @lamerock, it might be coming from a plugin that was installed. I can still see that the site is being redirected to http://crazytds.club/redirect.php when accessed on mobile. I have researched a bit and found the below link that might help fix the problem.

https://www.web-malware-removal.com/2020/wordpress-redirect-hack-2020/
