### ISSUE TITLE
How do I remove the "Republic of the Philippines" banner/text logo?

### ISSUE THREAD

**Issue by wassimpario** [iGovPhil/gwt-wordpress#71]
![logo](https://github.com/iGovPhil/gwt-wordpress/assets/6516521/d836d95b-00f1-4c0f-85fd-88ae5c98b6f1)

How do I remove the "Republic of the Philippines" banner/text logo?
I am trying to put our office's logo but the Banner text is still there. I really appreciate all the help as I am not even a coder.

**Comment by wassimpario** [comment]
I am trying to put our office's logo but the Banner text is still there. I really appreciate all the help as I am not even a coder.

**Comment by gumacahin** [comment]
There is a theme setting to hide this. However, you mentioned there's a fatal error when you access this page. You have to fix that first.

**Comment by itszaheerlgs** [comment]
navigate to theme option 

> ![logo](https://user-images.githubusercontent.com/6516521/248850549-d836d95b-00f1-4c0f-85fd-88ae5c98b6f1.png)
> 
> How do I remove the "Republic of the Philippines" banner/text logo? I am trying to put our office's logo but the Banner text is still there. I really appreciate all the help as I am not even a coder.
