### ISSUE TITLE
How do I fix the Theme options - critical error?

### ISSUE THREAD

**Issue by wassimpario** [iGovPhil/gwt-wordpress#72]
![themeoptionserror](https://github.com/iGovPhil/gwt-wordpress/assets/6516521/42b91084-475f-48f7-a414-2123ff8f9c31)

How do I fix this?

**Comment by gumacahin** [comment]
See https://github.com/iGovPhil/gwt-wordpress/issues/69

**Comment by wassimpario** [comment]
> See #69

Thank you. I'll try and follow this.
