### ISSUE TITLE
Why do I keep getting a GWT 25.3.3 critical error?

### ISSUE THREAD

**Issue by wassimpario** [iGovPhil/gwt-wordpress#73]
![error](https://github.com/iGovPhil/gwt-wordpress/assets/6516521/843fc6c2-26a1-4488-891b-0c117e3644e3)

I keep getting this error everytime I install GWT 25.3.3

**Comment by gumacahin** [comment]
There could be a number of reasons. If you can't code like you mentioned in the other issue it could be rather difficult. With that said, I tested gwt-25.3.3 theme in the latest WordPress/PHP releases and it does not cause a critical error on the front end. So it must be something else in your WP installation that is causing the issue. It would be helpful if you can turn on PHP's `display_errors` setting and also a system report of the PHP  version your are using and the plugins you have installed.

**Comment by wassimpario** [comment]
> 

I was able to access it again. Maybe the XAMPP that is installed is the one causing the error. I uninstalled my xampp and restarted my pc and was able to access the dashboard and the theme options.

**Comment by itszaheerlgs** [comment]
use 7.4.32 version of php
