### ISSUE TITLE
How do i remove the recent post part of the home page?

### ISSUE THREAD

**Issue by wassimpario** [iGovPhil/gwt-wordpress#74]
Please see attached image below.
![1](https://github.com/iGovPhil/gwt-wordpress/assets/6516521/8f7608df-cab3-4635-b38c-5eb176c1b631)

There's also no way for me to edit the CSS if ever that's the workaround. See image below.
![2](https://github.com/iGovPhil/gwt-wordpress/assets/6516521/4282ed3f-e530-4e28-bbf7-2a555c4e059e)

It's not also a widget so using Customize and Widgets won't work as well.

**Comment by gumacahin** [comment]
You need to edit the theme's `index.php` file.  Remove lines 22-39.

**Comment by wassimpario** [comment]
> You need to edit the theme's `index.php` file. Remove lines 22-39.

IT WORKED! THANK YOU SO MUCH!!!

**Comment by gumacahin** [comment]
No problem.
