### ISSUE TITLE
Masthead can't be edited

### ISSUE THREAD

**Issue by JetherPS** [iGovPhil/gwt-wordpress#88]
![image](https://github.com/iGovPhil/gwt-wordpress/assets/174141237/926997bf-c9d6-46d7-b871-894f89ae3b98)

When I am attempting to edit masthead thru Theme Options, this is always showing up.

**Comment by gumacahin** [comment]
We need more details. Please check the error logs.

**Comment by JetherPS** [comment]
where can i look for the logs?

**Comment by JetherPS** [comment]
![image](https://github.com/iGovPhil/gwt-wordpress/assets/174141237/d1f965c5-4c03-44aa-8ca8-642d245d9419)

**Comment by JetherPS** [comment]
[404.php.txt](https://github.com/user-attachments/files/16046972/404.php.txt)
[db-error.php.txt](https://github.com/user-attachments/files/16046973/db-error.php.txt)
these were the files i've seen so far. sorry i am new to this.

**Comment by jesteradduru** [comment]
> ![image](https://private-user-images.githubusercontent.com/174141237/344269895-926997bf-c9d6-46d7-b871-894f89ae3b98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODgwOTcsIm5iZiI6MTcxOTg4Nzc5NywicGF0aCI6Ii8xNzQxNDEyMzcvMzQ0MjY5ODk1LTkyNjk5N2JmLWM5ZDYtNDZkNy1iODcxLTg5NGY4OWFlM2I5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwMjM2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWU0YjZiNzJiNWIxYmU5NjMxODI2OTA3NTM2ZDAyODg4MTBlODNlYzdkNjkxMDAzMWU0Zjc0NDYwOTUyYTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.46qR6cpLm4Q5d833ZKdKbzCjsitXNCJe2R5VjlUc5fs)
> 
> When I am attempting to edit masthead thru Theme Options, this is always showing up.

same error. I'm getting this logs
![image](https://github.com/iGovPhil/gwt-wordpress/assets/36319308/fbc80db5-9603-41fe-a6e0-371ddcca804a)

**Comment by jesteradduru** [comment]
solved on #69

**Comment by JetherPS** [comment]
sorry, i can't follow the procedures. can you give me a guide of how to fix the theme options?

**Comment by JetherPS** [comment]
my godaddy.com plan doesnt have cpanel included. can you help me fix this??

**Comment by JetherPS** [comment]
> solved on #69

![image](https://github.com/iGovPhil/gwt-wordpress/assets/174141237/1da4cc94-246e-4d99-b119-659f7f173363)
where to put static here can you help me?

**Comment by JetherPS** [comment]
installer pla iedit hindi sa installed theme.. solved na. salamat.

**Comment by JetherPS** [comment]
installer pla iedit hindi sa installed theme.. solved na. salamat.
