### ISSUE TITLE
Error when going to theme options attempting to edit masthead

### ISSUE THREAD

**Issue by jesteradduru** [iGovPhil/gwt-wordpress#89]
> ![image](https://private-user-images.githubusercontent.com/174141237/344269895-926997bf-c9d6-46d7-b871-894f89ae3b98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODgwOTcsIm5iZiI6MTcxOTg4Nzc5NywicGF0aCI6Ii8xNzQxNDEyMzcvMzQ0MjY5ODk1LTkyNjk5N2JmLWM5ZDYtNDZkNy1iODcxLTg5NGY4OWFlM2I5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwMjM2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWU0YjZiNzJiNWIxYmU5NjMxODI2OTA3NTM2ZDAyODg4MTBlODNlYzdkNjkxMDAzMWU0Zjc0NDYwOTUyYTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.46qR6cpLm4Q5d833ZKdKbzCjsitXNCJe2R5VjlUc5fs)
> 
> When I am attempting to edit masthead thru Theme Options, this is always showing up.

same error. I'm getting this logs
![image](https://github.com/iGovPhil/gwt-wordpress/assets/36319308/fbc80db5-9603-41fe-a6e0-371ddcca804a)

_Originally posted by @jesteradduru in https://github.com/iGovPhil/gwt-wordpress/issues/88#issuecomment-2201717692_

**Comment by jesteradduru** [comment]
solved on #69

**Comment by JetherPS** [comment]
can you help me to edit this.. i dont have cpanel
