### ISSUE TITLE
Slider permalink bug

### ISSUE THREAD

**Issue by brasalan** [iGovPhil/gwt-wordpress#9]
I'll be using the latest version of the theme. So far, that's my only problem. With regards to the slider left button bug fix, when you're trying to navigate discontinuously the bug still recurs.

**Comment by v0j** [comment]
thank you for reporting this issue, may I know the version of the template that you are using?

**Comment by brasalan** [comment]
The latest version po. gwt-wordpress-master

**Comment by v0j** [comment]
I will try to replicate the issue.

for the mean time use the [GWT-2.0.2](https://github.com/iGovPhil/gwt-wordpress/tree/2.0.2).

**Comment by brasalan** [comment]
ok thanks!

**Comment by brasalan** [comment]
Sir/Ma'am, even your recommended GWT version's slider image links to the home page always. I dunno, I'm using Wordpress version 4.7.3 security version, the latest one

**Comment by v0j** [comment]
We released [new version](https://github.com/iGovPhil/gwt-wordpress/releases/latest) addressing the URL link for the slider.
