### ISSUE TITLE
GWT Warning & Undefined Variable

### ISSUE THREAD

**Issue by jcr93** [iGovPhil/gwt-wordpress#90]
Greetings!
I would like to ask for help with this.. I only know the basics when it comes to programming.. any help would be very much appreciated 😊 
![image](https://github.com/iGovPhil/gwt-wordpress/assets/175188019/0b5e6119-13be-414a-9560-3462b5d9f09c)
![image](https://github.com/iGovPhil/gwt-wordpress/assets/175188019/aa465446-98e6-4094-850a-70716302ebba)

**Comment by gumacahin** [comment]
Use this guide to get started: https://gumaca.gov.ph/dict-web-hosting/

**Comment by jcr93** [comment]
thanks much for this... already solved it ^^
